name: Go

on:
  push:
    branches: [ main ]
    paths: ['**.go', 'go.mod']
  pull_request:
    paths: ['**.go', 'go.mod', '.github/workflows/go.yml']
  workflow_dispatch:

jobs:

  test:
    name: Test
    strategy:
      matrix:
        go-version: [1.16.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - run: go test -v -race -coverprofile=coverage -covermode=atomic ./...

      - uses: codecov/codecov-action@v1
        with:
          name: coverage
          file: ./coverage

      - uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: ./coverage

  sonar:
    needs: test
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: coverage

      - uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: golangci/golangci-lint-action@v2
        with:
          version: latest
