name: Go

on:
  push:
    branches: [ main ]
    paths: ['**.go', 'go.mod']
  pull_request:
    paths: ['**.go', 'go.mod', '.github/workflows/go.yml']
  workflow_dispatch:

jobs:

  test:
    name: Test
    strategy:
      matrix:
        go-version: [1.16.x]
        platform: [ubuntu, macos, windows]
    runs-on: ${{ matrix.platform }}-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - run: go test -v -race -coverprofile=coverage -covermode=atomic ./...

    - uses: codecov/codecov-action@v1
      with:
        file: ./coverage

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-contrib/golangci-lint@v1
